# Generated by Django 4.2 on 2023-05-11 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fourbeing', '0006_remove_profile_username_alter_profile_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('url', models.CharField(max_length=200)),
                ('userPhoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fourbeing.profile')),
            ],
        ),
    ]
