# Generated by Django 4.2 on 2023-05-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0007_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='website',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
