# Generated by Django 4.2 on 2023-05-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0008_post_location_post_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='website',
        ),
    ]
