# Generated by Django 4.2 on 2023-05-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0011_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
