# Generated by Django 4.2 on 2023-05-11 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0012_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
    ]
