# Generated by Django 4.2 on 2023-05-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0013_remove_profile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
