# Generated by Django 4.2 on 2023-05-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_profile_username'),
        ('fourbeing', '0015_alter_photo_userphoto_alter_reply_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.profile'),
            preserve_default=False,
        ),
    ]
