# Generated by Django 4.2 on 2023-05-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0016_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='akatopi', max_length=50),
            preserve_default=False,
        ),
    ]
