# Generated by Django 4.2 on 2023-05-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0018_reply_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='username',
            field=models.CharField(default='akatopi', max_length=50),
            preserve_default=False,
        ),
    ]
