# Generated by Django 4.2 on 2023-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0020_alter_reply_love'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='love',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
