# Generated by Django 4.2 on 2023-05-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0026_alter_reply_post_alter_reply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='love',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
