# Generated by Django 4.2 on 2023-05-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0027_post_love'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='userPhoto',
        ),
    ]
