# Generated by Django 4.2 on 2023-05-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0028_remove_photo_userphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
