# Generated by Django 4.2 on 2023-06-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourbeing', '0029_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
