# Generated by Django 4.2 on 2023-05-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
