# Generated by Django 4.2 on 2023-05-15 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('useraccounts', '0002_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
